### PR TITLE
Combined changes from Tickets #16 and #23

### PR DESCRIPTION
**Pull request by erwintayag**
All changes for the Sidebar/Navbar combined

Reference: #16 and #23

### CODE REVIEW

**Comment by elmerbool** [comment]
Hi @erwintayag ,

I've made some changes to your pull request as a result of my code review. Can you please check if these are alright? I've removed some unused code / files.

https://github.com/ei8/cortex-diary/pull/42/files/6d301ad472aa1b2315adc16e394203377e5de37b..51c09d576e396d46c225db08024f0164e336a6ae

Kind regards,

**Review by elmerbool — CHANGES_REQUESTED** [review]
Hi @erwintayag, 

I've made some changes to your pull request as a result of my code review. Can you please check if these are alright? I've removed some unused code / files.

https://github.com/ei8/cortex-diary/pull/42/files/6d301ad472aa1b2315adc16e394203377e5de37b..51c09d576e396d46c225db08024f0164e336a6ae

Kind regards,

**Comment by erwintayag** [comment]
> Hi @erwintayag,
> 
> I've made some changes to your pull request as a result of my code review. Can you please check if these are alright? I've removed some unused code / files.
> 
> https://github.com/ei8/cortex-diary/pull/42/files/6d301ad472aa1b2315adc16e394203377e5de37b..51c09d576e396d46c225db08024f0164e336a6ae
> 
> Kind regards,

Hello Sir @elmerbool,
I've tested your changes on my local machine and it works fine. 
Thanks!

**Comment by elmerbool** [comment]
Hi @erwintayag ,

Thanks! I'll merge the changes then.

**Pull request merged**
